-- Felik Fvnky Store - Supabase schema
create extension if not exists pgcrypto;

create table if not exists products (
  id bigint generated by default as identity primary key,
  title text not null,
  creator text not null default 'FX Official',
  type text not null default 'remix',
  type_label text not null default 'REMIX',
  genre text not null default 'custom',
  genre_label text not null default 'Custom',
  price integer not null default 0 check (price >= 0),
  description text not null default '',
  preview_url text,
  featured boolean not null default false,
  active boolean not null default true,
  sales integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists orders (
  id uuid primary key default gen_random_uuid(),
  code text unique not null,
  product_id bigint references products(id) on delete set null,
  product_title text not null,
  style_label text,
  total integer not null check (total >= 0),
  customer_name text not null,
  phone text not null,
  song_title text not null,
  initials text not null,
  payment_method text not null,
  payment_reference text,
  note text,
  status text not null default 'PENDING_PAYMENT' check (status in ('PENDING_PAYMENT','PAID','QUEUED','IN_PROGRESS','REVISION','COMPLETED','CANCELLED')),
  reviewed boolean not null default false,
  created_at timestamptz not null default now(),
  paid_at timestamptz,
  completed_at timestamptz
);

create table if not exists reviews (
  id uuid primary key default gen_random_uuid(),
  order_id uuid unique not null references orders(id) on delete cascade,
  product_id bigint references products(id) on delete set null,
  rating integer not null check (rating between 1 and 5),
  review text not null default '',
  created_at timestamptz not null default now()
);

-- Public website can read active products and completed reviews.
alter table products enable row level security;
alter table orders enable row level security;
alter table reviews enable row level security;

create policy "public read active products" on products for select using (active = true);
create policy "public read completed reviews" on reviews for select using (true);

-- Orders are created from the website. In production, tighten this with an Edge Function
-- and payment webhook before launch. The service role must never be placed in frontend code.
create policy "public create orders" on orders for insert with check (true);

-- Admin work should be done through Supabase Auth + an Edge Function or a secured admin role.
-- Do NOT add update/delete policies for anonymous users.
